### PR TITLE
support hydrogen format

### LINKED ISSUE #2: Support Hydrogen's built-in multi-format notebook
See discussion here: https://github.com/nteract/hydrogen/issues/684

### PR DESCRIPTION
**Pull request by maximsch2**
Fixes #2 
cc: https://github.com/nteract/hydrogen/issues/684

Should also look into removing a ctrl-enter keymapping that interferes with Hydrogen.

### CODE REVIEW

**Comment by lgeiger** [comment]
👍 

Now the [note about language mappings](https://github.com/mpastell/language-weave#run-code-from-atom) can be removed.

**Comment by lgeiger** [comment]
To give more context on this, we recently introduced [first class support for multi language documents](https://medium.com/nteract/hydrogen-introducing-rich-multi-language-documents-b5057ff34efc).

This PR changes `language-weave` to adhere to the convention used by other languages, like [markdown](https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L873), [reStructuredText](https://github.com/Lukasa/language-restructuredtext/blob/master/grammars/restructuredtext.cson#L695) or [asciidoc](https://github.com/asciidoctor/atom-language-asciidoc/blob/master/grammars/language-asciidoc.cson#L4101).

**Comment by maximsch2** [comment]
Also, I've just verified that code execution through `julia-client` still works with this changes. So there is no downside, and the upside is that Hydrogen will also work transparently for code execution.

**Comment by mpastell** [comment]
Thanks, this is very useful. I use `julia-client` myself and I don't want to remove the `ctrl-enter` mapping. 

Do you have any ideas how to best support the same mapping for both julia-client and hydrogen?

**Comment by mpastell** [comment]
I pushed a new release 0.4.0 with this feature.

**Comment by maximsch2** [comment]
In terms of shortcuts - maybe having an option that would enable/disable those extra shortcuts? 

I haven't tested it yet, but I suspect there would be other instances when Hydrogen and julia-client will interfere with each other's `ctrl-enter` keymap, so it seems like a more general problem anyway. Maybe everyone should just add the mapping they want to their own keymaps.

**Pull request merged**
